config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get 'fire', to:'pages#fire'
  get 'diy', to:'pages#diy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def copyright_generator
    PinneyViewTool::Renderer.copyright 'Jonathan Pinney', 'All rights reserved.'
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HouseHacking 2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'styles/application', media: 'all', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>

    <%= render "shared/nav"%>

    <%= yield %>

    <%= render "shared/application_footer"%>
  </body>
</html>

app/views/pages/home.html.erb
<h2>Is you're house an asset or a liablity?</h2>

<h2>Are you sure?</h2>

<h4>What is house hacking?</h4>
<p>House hacking is the idea of utilizing a house as a true asset rather than the liability that it typically is.  We've all heard a house is an asset, and that isn't entirely untrue, but it is misleading.  Simply owning a house and living in it means that the house is a liability up to the point that it is sold.  At the point of sale, it switches to an asset because it has been a store of value during the duration of ownership.  All of the principal that was paid during that time, along with any appreciation in value, combines to create a return on ownership.
<br><br>
However, if a house is sold for less than the purchase value plus any additional investments in the house, then it was a liability only because the owner has lost money.  A critical point to understand, assets make you money liabilities cost you money.
<br><br>
The term house hacking has recently come into vogue in the popular lexicon, referring to the idea of turning a property into an asset during the period of ownership rather than at the point of sale.  This can be done in a variety of ways, but almost all involve some form of renting the home out.  The idea is especially popular among adhereants of the FIRE (Finanical Independance Retire Early) movement as it provides a second revenue stream alongside an existing job or business.  It also attracts a lot of DIYers (Do It Yourself), as making improviments on the home yourself, rather than hiring a contractor can save you a great deal of money, while improving the rental or resale value of the house substantially.
<br><br>
Much has been written already about house hacking, and a quick search for the term will get you lots of hits on articles and websites that are focused on it, though of a variety of quality and accuracy.  The purpose of this site is to collect in one place, the high quality content and make it easy to access from a single place.</p>

<h4>House Hacking Articles</h4>


<h4>The FIRE movement</h4>
<p>Life is about more than the drudgery of work, but we all need money to live.  The FIRE moment is based around the concept of making the dream of existing the rate race early a reality by living below your means, investing wisely and thinking differntly.</p>
<button>Learn More</button>

<h4>DIY Resources</h4>
<p>Whether you are remodeling a home or just making some small repairs, doing it yourself can save you a bundle of money.  Checkout the best resources to increase your knowledge and confidence for skipping the contractor and doing your own home improvements</p>
<button>Learn More</button>

app/views/shared/_application_footer.html.erb
<footer class="mastfoot mt-auto">
  <div class="inner">
    <p><br><%= copyright_generator %></p>
  </div>
</footer>

app/views/shared/_nav.html.erb
<div><%= link_to "Home", root_path %></div>
<div><%= link_to "FIRE", fire_path %></div>
<div><%= link_to "DIY", diy_path %></div>